### ISSUE TITLE
Feature Request: score logging

### ISSUE THREAD

**Issue by allenbdavis** [byronperpetua/hearts#2]
Simplest version would keep track of total scores, updating after each hand. Perhaps it could write to a local file.

More complex version would write each trick to local file, enabling a fun statistical analysis.

**Comment by byronperpetua** [comment]
Thinking about three tables produced per game. Columns follow the colon.

**Rounds**: round number, player, round score, cumulative score
**Passes**: round number, pass direction, from player, to player, card
**Plays**: round number, trick number, card number within trick, player, card, won trick

@allenbdavis can you think of anything else?

**Comment by allenbdavis** [comment]
I think that's pretty thorough. I'm imagining something like this:

YYMMDD_HHMMSS_round.csv

round_num, player, round_score, cum_score
1, Allen, 13, 13
1, Byron, 0, 0
1, Luke, 7, 7
1, Sam, 6, 6
2, Allen, 0, 13
2, Byron, 1, 1
2, Luke, 13, 20
2, Sam, 12, 18
[...]
